"""Per-episode file templates (plan.md §4.2) + the 12-episode seed-bank data.

``meta.toml`` is NOT a template — it is GENERATED from the ``Episode`` dataclass
(``episodes.py``, plan.md §4.1). This module owns the skeletons for the other
per-episode files: ``script.md``, the ``publish.md`` / ``brief.md`` placeholders,
and the ``project/index.html`` placeholder.

Render helpers take plain strings (never an ``Episode``) so this module never
imports ``episodes.py`` — ``episodes.py`` imports *us*, and a cycle would break
``cwp --help``'s fast import path.

The three root SoT docs (``voice.md``, ``build-contract.md``, ``pantsless-test.md``)
are NOT templates — they were authored once, directly at the repo root, in Step 1.
"""

from __future__ import annotations

import html

# TODO(Step 10): the 12-episode idea-bank seed data (plan.md §5.5 / Appendix D) lands
# here as structured rows (title, ingredient, effort, teaches, hook) seeded via
# episodes.create_episode.

_SCRIPT_MD = """\
# {title}

<!-- Read-aloud script + on-screen action notes (plan.md §4.2).
     Draft it in the channel voice: cwp draft {episode_id} script -->

## Hook

_(the first 15 seconds — why keep watching?)_

## Script

## On-screen actions

"""

# The sentinel drafting.py checks before appending title/description drafts into
# publish.md: present only while publish.md is still the placeholder below; `cwp publish`
# (Step 5) regenerates the file without it. A drift test asserts it stays in _PUBLISH_MD.
PUBLISH_PLACEHOLDER_SENTINEL = "<!-- PLACEHOLDER"

_PUBLISH_MD = """\
# {title} — publish metadata

<!-- PLACEHOLDER — `cwp publish {episode_id}` (Step 5) regenerates this file with
     paste-ready YouTube metadata from meta.toml + script.md. Edit meta.toml
     (title/hook/tags), not this file. -->
"""

_BRIEF_MD = """\
# {title} — build brief

<!-- PLACEHOLDER — `cwp brief {episode_id}` (Step 7) distills the kid transcript
     (capture/transcript.txt) into this brief, which `cwp build` turns into the
     toy at project/index.html. -->
"""


def render_script_md(*, title: str, episode_id: str) -> str:
    """The ``script.md`` skeleton: read-aloud script + on-screen action notes."""
    return _SCRIPT_MD.format(title=title, episode_id=episode_id)


def render_publish_md(*, title: str, episode_id: str) -> str:
    """The ``publish.md`` placeholder — real content is generated by ``cwp publish``."""
    return _PUBLISH_MD.format(title=title, episode_id=episode_id)


def render_brief_md(*, title: str, episode_id: str) -> str:
    """The ``brief.md`` placeholder — real content is generated by ``cwp brief``."""
    return _BRIEF_MD.format(title=title, episode_id=episode_id)


def render_index_html_placeholder(*, title: str, episode_id: str) -> str:
    """A minimal valid ``project/index.html`` placeholder.

    The verified toy is generated by ``cwp build`` (Step 9), which per §4.2 clobber
    protection only overwrites this page on a verified pass (or with ``--force``).
    Titles may contain HTML-special and non-ASCII characters — escaped here.
    """
    safe_title = html.escape(title)
    safe_id = html.escape(episode_id)
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        '<meta charset="utf-8">\n'
        f"<title>{safe_title}</title>\n"
        f"<h1>{safe_title}</h1>\n"
        f"<p>Placeholder for episode {safe_id} — the real toy is generated by\n"
        f"<code>cwp build</code> and replaces this page on a verified pass.</p>\n"
        "</html>\n"
    )
